### ISSUE TITLE
Rename kubevirt_raw module

### ISSUE THREAD

**Issue by tripledes** [kubevirt/ansible-kubevirt-modules#79]
Following the lead of kubernetes ansible modules, it'd be good idea to rename `kubevirt_raw` module to just `kubevirt`, as it seems the `raw`  portion of it scared potential users as they took it as unfinished or not something for the general public.

**Comment by lizsurette** [comment]
+1 to this. I had an additional comment on the naming of the modules that I wanted to add here. I'm happy to create a new issue if this shouldn't live here though :)

For clarity and consistency with other files/actions should we rename “kubevirt_raw_pvc.yml” to “kubevirt_pvc_create.yml”?

**Comment by mmazur** [comment]
Ever since the move to the dynamic api client for kubernetes, the `kubevirt_raw` module was on its way out, as in effect it became just a copy of the upstream `k8s` module. We're currently in the process of replacing `kubevirt_raw` with dedicated kubevirt and k8s modules. Once that's done, `kubevirt_raw` should be dropped to not cause confusion among users.
